# Site settings
title: truslines.network
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: Trustlines_Net
slack_invite_url:
github_username: trustlines-network
facebook_username: Trustlines.Network
subreddit_name: Trustlines
medium_name: Trustlines

collections:
  - faq
# Build settings
markdown: kramdown
